language: ruby
rvm:
  - 2.0.0

notifications:
  email:
    - shatrov@me.com

script:
  - "bundle exec rake spec SPEC=spec/models"
  - "SORCERY_ORM=mongoid bundle exec rake spec SPEC=spec/mongoid"
  - "SORCERY_ORM=mongo_mapper bundle exec rake spec SPEC=spec/mongo_mapper"
